Import('env', 'duplicate')

mylib_env = env.Clone()
mylib_env.Append(CPPDEFINES={'APP_NAME': 'Firmware'})
mylib_a, mylib_h = env.SConscript('../library/mylib/SConscript', exports={'env': mylib_env}, variant_dir='mylib', duplicate=duplicate)

env = env.Clone()
env.Append(CPPDEFINES={'APP_NAME': 'Firmware'})

sources = env.Glob('src/*.c')
program = env.Program('firmware', sources, CPPPATH=[mylib_h], LIBS=[mylib_a])

Return('program')
